# This file is meant to be used on JSMAPREDUCE - a free map reduce infrastructure. 
# Nevertheless, the curious can read through this file to understand the logic
# These map reduce files together count the number of 4 cards straight hands in the game of poker. This is not an actual category of hands in Poker. 
# The Poker hands will be generated by a kernel function available on the JSMAPREDUCE website.
# Python Reducer() : key is a made hand, e.g. 'flush' .
# Count up how many unique hands make e.g. a flush.



def Reducer(jsmr_context, key): 
  sum = 0; 
  while jsmr_context.HaveMoreValues(): 
    count_str = jsmr_context.GetNextValue() # value always in string form
    count = int(count_str) # convert to int for summing 
    sum += count 

  output_str = '%s:%d' % (key, sum) 
  jsmr_context.Emit(output_str) 

